// if(S<10){
//     console.log("s is less")   
// }
// else{
//     console.log("10 is greater")
// }
// let age = 10;

// let time = 15;
// if(time<=22){
//     console.log("good morning")
// }
// else if(time>=12 && time <=15){
//     console.log("good afternoon")
// }
// else{
//     console.log("good night")
// }

// let a=18;
// (a<20)?console.log("a is less than 20"):console.log("a is greater than 20")

// console.log(1);
// console.log(2);
// console.log(3);
// console.log(4);
// console.log(5);

// for(let i=1;i<=5;i++){
//     console.log(i)
// }

// for(let i=0;i<=10;i++){
//     console.log(i)
// }

// console.log("apple")
// console.log("orange")
// console.log("grapes")
// console.log("banana")

// let fruits=["apple","orange","grapes","banana"]
// for(let i=0; i<fruits.length;i++){
//     console.log(fruits[i]);
// }

// let num=[1,2,3,4,5,6,];
// for(i=0;i<num.length;i++){
//     if(num[i]%2==0){
//         console.log(`${num[i]} is even`)
//     }
//     else{
//     console.log(`${num[i]} is odd`)
// }

// }

// find the sum of the array
// let values = [1,2,3,4,5,6,7,8,9]
// let sum =0;
// for(let i=0;i<values.length;i++){
//     sum=sum+values[i];
// }
// console.log(sum);

// muliplication table
// for(let i=1;i<=5;i++){
//     for(j=1;j<=5;j++)
//         console.log(`${i} * ${j} =${i*j}`)
// }
// // reverse the string
// const str ="hello nirmala"

for(let i=1;i>=5;i++){
    for(j=1;j>=5;j++)
        console.log(`${i} * ${j} =${i*j}`)
}
// reverse the string
const str ="hello nirmala"